'use client';

import { useEffect, useState } from 'react';
import axios from 'axios';
import { getApiBase, getHRMEnabled, getHRMMmax, getHRMMmin } from '@/lib/config';

export default function QAInterface() {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [hrmOn, setHrmOn] = useState(false);
  const [hrmMmax, setHrmMmax] = useState<number>(6);
  const [hrmMmin, setHrmMmin] = useState<number>(2);

  // initialize HRM view-only params
  useEffect(()=>{
    try { setHrmOn(getHRMEnabled()); setHrmMmax(getHRMMmax()); setHrmMmin(getHRMMmin()); } catch {}
  }, []);

  const handleAsk = async () => {
    if (!question.trim()) return;

    setLoading(true);
    try {
      const API = getApiBase();
      const useHrm = getHRMEnabled();
      const response = await axios.post(
        `${API}/ask?question=${encodeURIComponent(question)}&use_hrm=${useHrm ? 'true' : 'false'}`
      );
      setAnswer(response.data);
    } catch (error) {
      console.error('Question failed:', error);
      alert('Failed to get answer. See console.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white p-6 rounded-lg shadow">
      <h2 className="text-2xl font-bold mb-4">Ask Questions</h2>
      
      <div className="space-y-3">
        <div className="flex flex-col sm:flex-row gap-2">
          <input
            type="text"
            placeholder="e.g., What is PMOVES?"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter') handleAsk(); }}
            className="flex-1 px-4 py-2 border rounded"
          />
          <button
            onClick={handleAsk}
            disabled={loading || !question.trim()}
            className="sm:w-auto w-full bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700 disabled:bg-gray-300"
          >
            {loading ? 'Thinking...' : 'Ask'}
          </button>
        </div>
        <div className="text-[12px] text-gray-600">
          Try: "What is PMOVES?", "Summarize API endpoints for Loan Servicing", or "Explain error CODE-123 from LMS logs".
        </div>
        {hrmOn && (
          <div className="text-[10px] text-gray-600 -mt-2 mb-1">HRM: Mmax {hrmMmax}, Mmin {hrmMmin}</div>
        )}
      </div>
      
      {answer && (
        <div className="mt-6 space-y-4">
          <div className="bg-blue-50 p-4 rounded">
            <h3 className="font-semibold mb-2 flex items-center gap-2">Answer: {answer?.hrm?.enabled && (typeof answer?.hrm?.steps === 'number') && (
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 border border-purple-200" title="HRM refinement steps">HRM {answer.hrm.steps}</span>
            )}</h3>
            <pre className="whitespace-pre-wrap text-sm">{answer.answer}</pre>
          </div>
          
          {answer.evidence && answer.evidence.length > 0 && (
            <div>
              <h3 className="font-semibold mb-2">Citations ({answer.evidence.length}):</h3>
              <div className="space-y-2">
                {answer.evidence.map((ev: any, idx: number) => {
                  const type = (ev.content_type || '').toString().toLowerCase();
                  const isFigure = type === 'figure';
                  const isTable = type === 'table';
                  const isText = type === 'text';
                  const page = ev?.coordinates?.page;
                  return (
                    <div key={idx} className="bg-gray-50 p-3 rounded text-sm">
                      <div className="flex items-center gap-2 mb-1">
                        <p className="font-medium text-blue-600 mr-2">{ev.locator}</p>
                        {isFigure && (
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-orange-100 text-orange-700 border border-orange-200">Figure</span>
                        )}
                        {isTable && (
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-700 border border-emerald-200">Table</span>
                        )}
                        {isText && (
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-100 text-slate-700 border border-slate-200">Text</span>
                        )}
                        {ev.vlm && (
                          <span title="Generated by Granite Docling" className="text-[10px] px-2 py-0.5 rounded-full bg-indigo-100 text-indigo-700 border border-indigo-200">VLM</span>
                        )}
                        {page && (
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-gray-100 text-gray-700 border border-gray-200">Page {page}</span>
                        )}
                      </div>
                      <p className="text-gray-600 mt-1">{(ev.preview || '').substring(0, 200)}...</p>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
