'use client';

import { useState } from 'react';
import axios from 'axios';

export default function QAInterface() {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  const handleAsk = async () => {
    if (!question.trim()) return;

    setLoading(true);
    try {
      const API = process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:8000';
      const response = await axios.post(
        `${API}/ask?question=${encodeURIComponent(question)}`
      );
      setAnswer(response.data);
    } catch (error) {
      console.error('Question failed:', error);
      alert('Failed to get answer. See console.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white p-6 rounded-lg shadow">
      <h2 className="text-2xl font-bold mb-4">Ask Questions</h2>
      
      <div className="space-y-4">
        <div>
          <input
            type="text"
            placeholder="e.g., what is the total ROAS?"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && handleAsk()}
            className="w-full px-4 py-2 border rounded"
          />
        </div>
        
        <button
          onClick={handleAsk}
          disabled={loading || !question.trim()}
          className="w-full bg-green-600 text-white py-2 rounded hover:bg-green-700 disabled:bg-gray-300"
        >
          {loading ? 'Thinking...' : 'Ask'}
        </button>
      </div>
      
      {answer && (
        <div className="mt-6 space-y-4">
          <div className="bg-blue-50 p-4 rounded">
            <h3 className="font-semibold mb-2">Answer:</h3>
            <pre className="whitespace-pre-wrap text-sm">{answer.answer}</pre>
          </div>
          
          {answer.evidence && answer.evidence.length > 0 && (
            <div>
              <h3 className="font-semibold mb-2">Citations ({answer.evidence.length}):</h3>
              <div className="space-y-2">
                {answer.evidence.map((ev: any, idx: number) => {
                  const type = (ev.content_type || '').toString().toLowerCase();
                  const isFigure = type === 'figure';
                  const isTable = type === 'table';
                  const isText = type === 'text';
                  const page = ev?.coordinates?.page;
                  return (
                    <div key={idx} className="bg-gray-50 p-3 rounded text-sm">
                      <div className="flex items-center gap-2 mb-1">
                        <p className="font-medium text-blue-600 mr-2">{ev.locator}</p>
                        {isFigure && (
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-orange-100 text-orange-700 border border-orange-200">Figure</span>
                        )}
                        {isTable && (
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-700 border border-emerald-200">Table</span>
                        )}
                        {isText && (
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-100 text-slate-700 border border-slate-200">Text</span>
                        )}
                        {ev.vlm && (
                          <span title="Generated by Granite Docling" className="text-[10px] px-2 py-0.5 rounded-full bg-indigo-100 text-indigo-700 border border-indigo-200">VLM</span>
                        )}
                        {page && (
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-gray-100 text-gray-700 border border-gray-200">Page {page}</span>
                        )}
                      </div>
                      <p className="text-gray-600 mt-1">{(ev.preview || '').substring(0, 200)}...</p>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
